### ISSUE TITLE
Pinned tabs are not tall enough when tab strip is in overflow mode

### ISSUE THREAD

**Issue by garrett** [kurogetsusai/firefox-gnome-theme#11]
When there are enough tabs to cause Firefox's overflow to happen, pinned tabs are no longer tall enough.

(This is possibly related to #8.)

**Comment by lunakurame** [comment]
Turned out not to be related to #8, I just accidentally broke it in commit 476ef93cc1f5dc8878aeaaa122ca97606e01fdbb. It should be working properly now, thanks for reporting that bug.
