### ISSUE TITLE
Better support for the menu bar

### ISSUE THREAD

**Issue by YarnSphere** [kurogetsusai/firefox-gnome-theme#39]
Currently this is what happens when the menu bar is shown by pressing `alt` or ticking the `Menu Bar` option (in FF 60.0 with CSD enabled):
![screenshot from 2018-05-14 10-14-58](https://user-images.githubusercontent.com/8314616/39985751-de3590ec-575f-11e8-8a0a-716d4f023fca.png)

I'm not saying that it should look perfect since GNOME applications have no menu bar anyway, but perhaps it could look a little less broken? :)

Thank you for your work!

**Comment by rafaelmardojai** [comment]
Please, test #40 and let me know.

**Comment by YarnSphere** [comment]
Tested; LGTM!
Thank you for your work!

**Comment by lunakurame** [comment]
Thanks for reporting this bug and thank you @rafaelmardojai for fixing it! I'm surprised you found a way to even add CSD autodetection, are there any known bugs? It looks stable to me, maybe it could even replace all those manual CSD switches completely, or at least land in the new `ui/recommended-features.css` file when we add it (#36).

**Comment by rafaelmardojai** [comment]
@kurogetsusai there's no known bugs and is working on Stable, Beta & Nightly.

Maybe we can wait to one more version, and if Mozilla don't break nothing we can default `experimental-auto-csd.css` and include it to core when #36 is done.
