### ISSUE TITLE
Search bar is smaller than location bar

### ISSUE THREAD

**Issue by platypro** [kurogetsusai/firefox-gnome-theme#42]
The location bar is resized properly but the search bar isn't. See screenshot.

![smallbar](https://user-images.githubusercontent.com/15664710/40299934-b0084f6a-5c9c-11e8-9e9f-3a58a42f723d.png)

**Comment by lunakurame** [comment]
Just fixed it, should look the same as the location bar now. Thanks for reporting this bug.
