### ISSUE TITLE
Location bar hidden in fullscreen (F11) mode when mouse hovered over

### ISSUE THREAD

**Issue by ashwinvis** [kurogetsusai/firefox-gnome-theme#45]
Only the tab bar reappears on mouse hover. This is how my `customChrome.css` looks like. 

```css
@import "ui/gnome-3.26-light.css"; /**/
@import "ui/experimental-auto-csd.css"; /**/
@import "ui/private-urlbar.css"; /**/
```

I am right now on ArchLinux with KDE Plasma 5.12.5, with Firefox 60.0.1

**Comment by lunakurame** [comment]
I can confirm this. Happens only if CSD is enabled, caused by 76d78304a69b64b7b51c4cb95b664c270fee67d9, looks like pull request #40 fixed a lot of problems but added this bug. Should be easy to override since we can detect fullscreen with `:root[inFullscreen]`.

**Comment by lunakurame** [comment]
Fixed, thanks for reporting.
