### ISSUE TITLE
Faint circle (from default Firefox theme) when hovering over back button

### ISSUE THREAD

**Issue by MrPowerMac** [kurogetsusai/firefox-gnome-theme#50]
When hovering over the back button, a faint circle is visible around the arrow icon, which is an artifact from the default Firefox theme. (This can be demonstrated by changing "Density" to "Compact" in the Customize menu; the circle stops appearing since it is not part of the back button with that density.)
![Screenshot depicting faint circle](https://user-images.githubusercontent.com/23667741/41323641-9e292c9a-6e64-11e8-84c4-1230bf9ebec2.png)
Obviously this circle is not a part of the Adwaita styling, and should be removed if possible.

**Comment by lunakurame** [comment]
Oh I see. I recently refactored this part of code (#36), I changed a lot of selectors and they actually work nicer now, but I guess the circle came back and I didn't notice it. Thanks, I'll fix it soon.

**Comment by rafaelmardojai** [comment]
Fixed
