### ISSUE TITLE
Close Button on Firefox 65 Is Larger than the CSD

### ISSUE THREAD

**Issue by Saroufim** [kurogetsusai/firefox-gnome-theme#52]
With the update to Firefox 65, the close button overlaps the tabs bar and appears to have its own styling and color

**Comment by rafaelmardojai** [comment]
Can you try my fork? https://github.com/rafaelmardojai/firefox-gnome-theme
It has some improvements and fixes, currently only works fine with gnome-3.26-light. Next week i will finish updating dark theme.

**Comment by Saroufim** [comment]
I'm using the dark theme hence why the issue persists on your fork too. I'll wait for the fix next week then

**Comment by rafaelmardojai** [comment]
Hey, can you test last changes in my fork?

![captura de pantalla de 2018-11-04 11-53-59](https://user-images.githubusercontent.com/6210397/47967161-77eaf280-e028-11e8-91a5-456bacbd19f2.png)

**Comment by Saroufim** [comment]
The difference is there. The close button is almost inline with the rest but not perfectly.
![captura de pantalla de 2018-11-04 22-10-10](https://user-images.githubusercontent.com/4712288/47969375-13a74d80-e07f-11e8-9b11-df6021cdd1d2.png)

**Comment by rafaelmardojai** [comment]
Can you give me more info about your system? 
I can't reproduce the issue running FF65 over Fedora 28 / GTK 3.28.

**Comment by rafaelmardojai** [comment]
Can you also provide me what lines do you have uncommented in your `userChrome.css`?

**Comment by Saroufim** [comment]
Sorry for the delay in getting back to you. I just updated firefox today and the CSD is completely gone. It seems like the address bar and the tabs bar have been merged into one. I'm using Firefox 65 flatpak from Xhorak (https://github.com/xhorak/firefox-devedition-flatpak) on Fedora 29

**Comment by rafaelmardojai** [comment]
Yeah, i noticed it yesterday.
Currently i don't know if i going to continue working on this. I have many issues with FF (performance, sound, etc) and i'm considering switch to Opera. If i stay, probably i will be doing a hard fork, because the original author has been inactive for 5 months.

**Comment by lunakurame** [comment]
@rafaelmardojai, I stopped using GNOME and then I kinda stopped using Firefox too, I switched to [surf](https://surf.suckless.org) instead. I still have Firefox as my secondary browser, but I barely use it. If you decide to continue working on this theme, I can give you Collaborator permissions, so you can push directly to this repo and manage issues. If you want, of course.

**Comment by smithfred** [comment]
@kurogetsusai - give me collab perms too if you can (I did a bunch of the fixes for GNOME 3.26 etc.)

**Comment by rafaelmardojai** [comment]
Currently i stopped using Firefox, at least until it works well for me. So no plans on working this theme on my side.

@smithfred if you will continue working on this theme, my fork have some fixes and improvements, and was working on FF stable last time i checked it.

**Comment by lunakurame** [comment]
@smithfred Invite sent, welcome aboard! :D Feel free to push fixes for any issues you may find. Make sure the license of everything you push allows using it under the Unlicense (public domain), eg. I'm not sure about those icons you had in your repo the last time I checked it. But I also haven't checked it, so I don't know. Alternatively we can switch to GPL v3 if that makes it easier.

**Comment by rafaelmardojai** [comment]
Please test last changes on repo.

Currently looks like this for me:
![captura de pantalla de 2019-02-16 21-52-27](https://user-images.githubusercontent.com/6210397/52907720-35df6880-3235-11e9-9bf4-fcbdd7f1e233.png)
