### ISSUE TITLE
Doesn't work at all with CSDs on Firefox 65

### ISSUE THREAD

**Issue by JaneSmith** [kurogetsusai/firefox-gnome-theme#53]
I'm running Firefox 65.0 on Arch Linux. If I have the Firefox titlebar enabled, then it works fine. However, if I disable the titlebar in order to have the CSD approach, I end up with this:

![screenshot from 2019-02-12 20-22-18](https://user-images.githubusercontent.com/10216091/52665662-04e4f800-2f04-11e9-8815-7104560d2c26.png)

As you can see, I have a completely blank headerbar. This happens if I uncomment either the `@import "ui/experimental-auto-csd.css";` or `@import "ui/csd.css";` line in `userChrome.css`.

I've also tried the fork by @rafaelmardojai and I have exactly the same issue there.

**Comment by rafaelmardojai** [comment]
This is a known issue. Firefox reworked its CSD and break this theme.

But nobody is working on this theme now so...

**Comment by JaneSmith** [comment]
That's really disappointing. I loved this theme back it worked. It made Firefox into a great alternative to GNOME Web.

**Comment by rafaelmardojai** [comment]
I decided to take this project again.
Please test last changes on repo.

Currently looks like this for me:
![captura de pantalla de 2019-02-16 21-52-27](https://user-images.githubusercontent.com/6210397/52907720-35df6880-3235-11e9-9bf4-fcbdd7f1e233.png)

**Comment by Saroufim** [comment]
I can't seem to apply the updates. The old theme seems to be hardwired now. Even if I delete the chrome folder, Firefox won't revert back to its original look. I wonder if this is an issue with Flatpak or firefox.

**Comment by acch** [comment]
Great @rafaelmardojai - thanks for your efforts! 

Looks promising. Maximized firefox windows look perfect. However, with non-maximized windows the tabs seem to be too high and overlap the address bar for me:
![image](https://user-images.githubusercontent.com/11490209/52911782-05d1ad00-32a9-11e9-8799-905348aefc3d.png)

...but that's just a minor glitch. Firefox Gnome Theme is usable for me again.
BTW I'm in Arch Linux, Firefox 65.0.1

**Comment by rafaelmardojai** [comment]
@acch Fixed!

**Comment by acch** [comment]
Awsome! Looks flawless to me.

**Comment by rafaelmardojai** [comment]
@Saroufim i installed Firefox flatpak (https://firefox-flatpak.mojefedora.cz) and theme works like expected.
