### ISSUE TITLE
Fullscreen bugs

### ISSUE THREAD

**Issue by lionirdeadman** [kurogetsusai/firefox-gnome-theme#56]
When fullscreen, 

- Windows controls appear in the bottom bar
- With the titlebar removed, there's a weird space left.

![Screenshot-20190313182715-1280x1024](https://user-images.githubusercontent.com/39467792/54319066-bb4d0300-45be-11e9-8834-65242f47f20d.png)

**Comment by rafaelmardojai** [comment]
Fixed.
![Captura de pantalla de 2019-04-20 10-45-20](https://user-images.githubusercontent.com/6210397/56459454-879d8f80-6359-11e9-9b2d-0ea5a6914ea2.png)

Pd: There is an issue when `hide-single-tab.css` is active, if you have a single tab, header bar will not shown when full screen is active.

**Comment by rafaelmardojai** [comment]
Temporal fix for `hide-single-tab.css` ready.
