### ISSUE TITLE
CSD Buttons on the Left

### ISSUE THREAD

**Issue by willmtemple** [kurogetsusai/firefox-gnome-theme#58]
On Firefox 66.0.3 for Fedora 30, I am using this theme, but I can't seem to get the titlebar buttons (close, maximize, and minimize) to go to the left side of the headerbar. This is different from Elementary (where the maximize button is on the right side and the close button is on the left), as all of my buttons are on the left.

They _do_ show in the correct order, with the close button on the left of all the other buttons, but on the right side of the headerbar as a group:

![image](https://user-images.githubusercontent.com/666532/57201411-dcdec100-6f55-11e9-9264-f259879ed26c.png)

I would like it to display like this:

![image](https://user-images.githubusercontent.com/666532/57201429-0ef02300-6f56-11e9-976f-4f58fd2c661a.png)

There are some userChrome snippets out there on the web that supposedly do this, but none work for me that I've found. I'm not sure if that's because they're incompatible with the GNOME theme or if they're for an older version of firefox.

**Comment by rafaelmardojai** [comment]
Working on this.

**Comment by rafaelmardojai** [comment]
![Captura de pantalla de 2019-05-05 19-43-27](https://user-images.githubusercontent.com/6210397/57202710-20452980-6f6e-11e9-8746-7cd01c03e883.png)
Here some progress.

**Comment by rafaelmardojai** [comment]
![Captura de pantalla de 2019-05-06 21-45-52](https://user-images.githubusercontent.com/6210397/57268163-6373cb00-7048-11e9-9a1f-82f9e5692c10.png)
@willmtemple Looks good enough for you?
I'm going to push it to repo soon.

**Comment by rafaelmardojai** [comment]
![Captura del escritorio de 06-05-19 22_22_47](https://user-images.githubusercontent.com/6210397/57271848-c53b3180-7056-11e9-8fdd-e07675c95971.gif)
@willmtemple Fixed, please test latest commits.

**Comment by willmtemple** [comment]
Working perfectly here. Thanks!
