### ISSUE TITLE
Question: Buttons in window without the titlebar

### ISSUE THREAD

**Issue by btd1337** [kurogetsusai/firefox-gnome-theme#63]
Is it possible to have the `minimize` and `maximize` icon buttons in a window without the titlebar?

**With Titlebar**
![Captura de tela de 2019-07-13 17-11-28](https://user-images.githubusercontent.com/11943860/61176100-4b14b500-a591-11e9-8136-c9bb57b5bd4f.png)

**Without Titlebar**
![Captura de tela de 2019-07-13 17-11-09](https://user-images.githubusercontent.com/11943860/61176101-4b14b500-a591-11e9-9095-4c183b47332c.png)

![Captura de tela de 2019-07-13 17-13-28](https://user-images.githubusercontent.com/11943860/61176118-916a1400-a591-11e9-82ab-0a0940394f2f.png)

**Comment by rafaelmardojai** [comment]
This theme is almost unmaintained, now i'm working here: https://github.com/rafaelmardojai/firefox-gnome-theme.

But if you want to continue using this repo for GNOME 3.28 style i can consider pushing a fix.

**Comment by btd1337** [comment]
In the other repository is all ok! Thanks man!
