### ISSUE TITLE
Quit Minimize ect... buttons displayed on a little bar on the top of url adress

### ISSUE THREAD

**Issue by Millie290** [kurogetsusai/firefox-gnome-theme#64]
All in title a little picture : 
![bug firefox gnometheme](https://user-images.githubusercontent.com/44525457/64369932-9ab9af00-d01d-11e9-8b0a-859e5b0246cf.png)

**Comment by rafaelmardojai** [comment]
This theme is unmaintained, try with https://github.com/rafaelmardojai/firefox-gnome-theme
