### ISSUE TITLE
The authorization popup for allowing use of camera and micro won't show

### ISSUE THREAD

**Issue by psychoslave** [kurogetsusai/firefox-gnome-theme#65]
Hello,

It seems that the theme prevent the display of popup  for allowing use of camera and micro.

To reproduce it, go for example to https://meet.jit.si/gnome-firefox-theme

At least for me, it doesn't show any popup, as it should do. So the service can't be used. Running Firefox with an other profile without firefox-gnome-theme (`Firefox -P`) doesn't come with such a defect. Interference caused by an other extension is not impossible but seems to me quite unlikely: gnome-firefox-theme is the only extension I use which change the Firefox interface.

**Comment by rafaelmardojai** [comment]
All work fine on my side.

![Captura de pantalla de 2020-04-21 09-44-07](https://user-images.githubusercontent.com/6210397/79880201-4e0cc380-83b5-11ea-97b7-d947d0220895.png)

**Comment by rafaelmardojai** [comment]
This theme is unmaintained. Please try with new upstream https://github.com/rafaelmardojai/firefox-gnome-theme. If issue persists open an issue there.

**Comment by psychoslave** [comment]
Ok, I'll do that.

**Comment by psychoslave** [comment]
@rafaelmardojai actually I was using the right repository in my install. It's only the issue place that I mistargeted. Thus said, I went into the chrome directory, checkout master, pulled the last version, restarted firefox, and thereafter was unable to reproduce the bug. So it's seem like there is no reason to duplicate the issue in the maintained repository.
