### ISSUE TITLE
Tab drag and drop collapses height

### ISSUE THREAD

**Issue by garrett** [kurogetsusai/firefox-gnome-theme#8]
When dragging tabs to re-order, all tabs — the active being dragged as well as the inactive tabs in the tab strip —  collapse their height to the label.

**Comment by lunakurame** [comment]
I couldn't reproduce this bug for quite a while, on Firefox 57 everything seems to work well, but now I finally noticed it on FF 58 and 59. The theme does have a few problems on FF 58+, I'll take a look at them. Thanks for reporting.

**Comment by lunakurame** [comment]
Looks like it works now, thanks for reporting it.

**Comment by lunakurame** [comment]
Oops, my bad. It was fixed in the `hide-single-tab.css` module, but if it was disabled, that bug was still present. I moved the fix to the right place now.
